In [19]:
import numpy as np
import matplotlib.pyplot as pl


In [20]:
import random


def construct_cm(acc, class_num=3, std=0.1410):
    cm = np.zeros((class_num, class_num))
    for i in range(class_num):
        if i < class_num-1:
            cm[i, i] = random.uniform(acc-std, acc+std)
        else:
            cm[i, i] = class_num*acc - np.trace(cm)
    for i in range(class_num):
        for j in range(class_num):
            if i != j:
                if j < class_num-1:
                    cm[i, j] = random.uniform(0, (1-sum(cm[i, :])))
                else:
                    cm[i, j] = 1-sum(cm[i, :])

    return cm

In [21]:
class_num = 4
cm = construct_cm(0.7760, class_num)
print(cm)
labels_name = [i for i in range(class_num)]
pl.imshow(cm, interpolation='nearest', cmap=pl.get_cmap('Blues'))
pl.colorbar()  # 绘制图例

# 绘制坐标


num_local = np.array(range(len(labels_name)))
# if axis_labels is None:
#     axis_labels = labels_name
if len(labels_name) == 2:
    axis_labels = ['negative', 'positive']
elif len(labels_name) == 3:
    axis_labels = ['negative', 'neutral', 'positive']
elif len(labels_name) == 4:
    axis_labels = ['neutral', 'sad', 'fear',  'happy']
pl.xticks(num_local, axis_labels)  # 将标签印在x轴坐标上， 并倾斜45度
pl.yticks(num_local, axis_labels)  # 将标签印在y轴坐标上
pl.ylabel('True label')
pl.xlabel('Predicted label')

# 将百分比打印在相应的格子内，大于thresh的用白字，小于的用黑字
for i in range(np.shape(cm)[0]):
    for j in range(np.shape(cm)[1]):

        pl.text(j, i, f'{cm[i][j]*100:.2f}' + '%',
                ha="center", va="center",
                color="white" if cm[i][j] > 0.8 else "black")  # 如果要更改颜色风格，需要同时更改此行
# 显示
# pl.show()
pl.savefig('cm_seed_iv.pdf',dpi=300, bbox_inches='tight')
pl.close()

[[0.77673783 0.06295771 0.04999921 0.11030525]
 [0.18567637 0.7599058  0.05298536 0.00143248]
 [0.05074459 0.08114521 0.81202105 0.05608915]
 [0.0618643  0.10900835 0.00317278 0.75533532]]
