In [3]:
import numpy as np

# Define the labels from the user's image
labels = [
    "FP1", "FPZ", "FP2", "AF3", "AF4", "F7", "F5", "F3", "F1", "FZ", "F2", "F4",
    "F6", "F8", "FT7", "FC5", "FC3", "FC1", "FCZ", "FC2", "FC4", "FC6", "FT8",
    "T7", "C5", "C3", "C1", "CZ", "C2", "C4", "C6", "T8", "TP7", "CP5", "CP3",
    "CP1", "CPZ", "CP2", "CP4", "CP6", "TP8", "P7", "P5", "P3", "P1", "PZ", "P2",
    "P4", "P6", "P8", "PO7", "PO5", "PO3", "POZ", "PO4", "PO6", "PO8", "CB1",
    "O1", "OZ", "O2", "CB2"
]

# The number of labels determines the size of the adjacency matrix
n_labels = len(labels)

# Create a random adjacency matrix
# To make it more realistic, we can assume that the brain connectivity graph is sparse
# Therefore, we will create a matrix with more zeros than ones
# Using a probability of 0.1 for an edge to exist
adjacency_matrix = np.random.choice(
    [0, 1], size=(n_labels, n_labels), p=[0.9, 0.1])
print(adjacency_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
